# site settings
title: Galen Savidge
subtitle:
email: galensavidge@gmail.com
description: Robotics Engineering Student and Jazz Pianist
baseurl: "" # the subpath of your site, e.g. /blog
url: 'https://www.galensavidge.com/' # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
author: Galen Savidge
street_address:
city: Berkeley
state: CA
zip_code: 94708
country: United States
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 12

# social settings
500px_url:
facebook_url:
github_url: https://github.com/galensavidge
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/galen-savidge/
pinterest_url:
slack_url: 
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
